# Generated by Django 6.0.2 on 2026-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
