# Generated by Django 6.0.2 on 2026-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
