# Generated by Django 6.0.2 on 2026-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('purchase_price', models.BigIntegerField(blank=True, null=True)),
                ('current_value', models.BigIntegerField(blank=True, null=True)),
                ('total_invested', models.BigIntegerField(blank=True, null=True)),
                ('monthly_mortgage', models.IntegerField(blank=True, null=True)),
                ('monthly_fee', models.IntegerField(blank=True, null=True)),
                ('monthly_rent', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
